### ISSUE TITLE
Úprava seznamu příloh

### ISSUE THREAD

**Issue by JanMate** [tenhobi/bachelors-thesis#7]
Nezapomeň změnit název souboru v tabule attachments z thesis.pdf na BP_Bittner_Jan.pdf nebo podobně podle toho, jak bude výsledný soubor jmenovat. [atachment.tex](../blob/master/parts/attachment.tex)
Není to žádná velká chyba (taky jsem s tím prošel), ale co si budem povídat, nevypadá to hezky. :)

**Comment by tenhobi** [comment]
Attachment jsem zatím nechal po vzoru ukázkového dokumentu.

Opravím, díky za podnět. :+1:
